### ISSUE TITLE
two buzzers

### ISSUE THREAD

**Issue by JE521** [PeCeSe/Arduino-piezo-music#1]
I have 2 buzzers that both work. How would I go about having both buzzers playing 2 different parts at the same time. Thanks.

**Comment by PeCeSe** [comment]
Unfortunately, you won't be able to do that with this library out of the box. Arduino is not multithreaded, so generally doing two things at the same time is difficult. However, I think it should be possible, by either having two Arduinos each connected to their own buzzer playing different parts, or playing on two buzzers from one Arduino by "switching back and forth" between melodies. (Meaning, if you want to play C on buzz1 and G on buzz2 starting at the same time, you need to start one of them first, and the second the moment after. Hopefully it will go so fast that you won't hear the small delay) 

However, like I said, this can't be cone with this library as it is, but feel free to tweak it and if you get it to work I would love a PR here so I can extend the library :)
